apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omeyazic/gitops-1-manifests.git
    targetRevision: main
    path: test-application
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
