all:
  children:
    k3s_cluster:
      children:
        control_plane:
          hosts:
            gitops-control-plane:
              ansible_host: 192.168.2.18
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
              node_ip: 192.168.2.18
        workers:
          hosts:
            gitops-worker-node:
              ansible_host: 192.168.2.19
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
              node_ip: 192.168.2.19
      vars:
        ansible_python_interpreter: /usr/bin/python3
